### ISSUE TITLE
rogudators_speech_bubble_generator.py line 136 has indent instead of 8 spaces

### ISSUE THREAD

**Issue by hsandt** [rogudator/rogudators_speech_bubble_generator#1]
Some users commenting on the [setup video](https://www.youtube.com/watch?v=1LkmuH2tbZc) noticed that the plugin is greyed out in the list of plugins in Krita.

I inspected the code and found out that line 136 in rogudators_speech_bubble_generator.py has an indent instead of 8 spaces (it shows when you set indent to show as 4 spaces, or in my case a linter will underline it in red).

See https://github.com/rogudator/rogudators_speech_bubble_generator/blob/main/rogudators_speech_bubble_generator/rogudators_speech_bubble_generator.py#LL136C1-L136C1

before `self.tailSpinBox.setMaximum`

Fixing it does fix the gray out in Krita, and the plugin works after restart.

**Comment by rogudator** [comment]
Okay, seems like it's already fixed on gumroad. But I didn't push the changes to main. Now everything should be up to date.

**Comment by hsandt** [comment]
Thanks!
